### PR TITLE
EDU-10497 New Checkout Settings for Bot Attack Protection

### PR DESCRIPTION
**Pull request by geisecosta**
#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

### CODE REVIEW

**Comment by geisecosta** [comment]
> Oi, @geisecosta ! Como conversamos, precisamos também documentar os novos campos na response do GET de orderForm configuration.

Já esta adicionado.

**Review by PedroAntunesCosta — APPROVED** [review]
LGTM

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
When it comes to responses, we don't include examples in the field schema, only `type` and `description`. The example is for the whole response body. (see our openapi template for more info)

**Review by PedroAntunesCosta — APPROVED** [review]
LGTM

**Pull request merged**
